### ISSUE TITLE
Projects using MY-BASIC

### ISSUE THREAD

**Issue by jacmoe** [paladin-t/my_basic#13]
I am using MY-BASIC in my [nasl](https://github.com/jacmoe/nasl) project - and I love how light-weight and practical it is - great work! 😃 

If you want to add scripting to your project, why not use a language that is BASIC ?
Much better than JavaScript, and other popular scripting languages, even Lua!

Are there other people using MY-BASIC ?
If so, then I would like a Wiki page dedicated to MY-BASIC projects. :)

Thanks for developing MY-BASIC 👍

**Comment by paladin-t** [comment]
\(^  ^)/  CHEERS! I'm proud to know it helped you building the nice nasl project. Actually I'm developing something 8-bit/16-bit, an integrated game and app development software, with user programmability with BASIC. Still WIP, and an early stage. Maybe I'll show off a runnable later.

I know some people using MY-BASIC with different kinds of projects, but I'm not sure how they would like to share their ones. A dedicated gallery wiki page would be cool. In fact there was a "Who are using" wiki page when the MY-BASIC project was still hosted on the Google Code, but nobody appended anything, it's not weird considering MY-BASIC was not as complete as now. Even now I'm not sure about it.

So how about posting your projects following this page. Guys please don't be reserved. I'll make a dedicated wiki page instead of this issue page if there will be enough audiences.

Have fun.

**Comment by ScriptBasic** [comment]
I have used **My-BASIC** as an extension module to **Script BASIC** until I created the **SBT** extension module that runs dynamic scripts as threads.

**Comment by paladin-t** [comment]
Thank you John for the information.

**Comment by paladin-t** [comment]
All right. I made a repo for the [showcase](https://github.com/my-basic/showcase/). PR welcomed.
Correct me if I've made any mistake.
