### ISSUE TITLE
any plans to ?

### ISSUE THREAD

**Issue by denisdemaisbr** [paladin-t/my_basic#18]
- endianess support
- multi-thread safe
- network support 
- http client (sync or async)

**Comment by paladin-t** [comment]
- endianess support. Not yet, but considerable.
- multi-thread safe. No. At least not now.
- network support. Yes.
- http client (sync or async). Yes.

The last two Network and HTTP will be implemented in another extended library, instead of this kernel repo. I'll also introduce a Coroutine feature for concurrency and some other threaded IO operations in that extended lib too.
