### ISSUE TITLE
Modify "+" operator to automatically do STR conversions?

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#40]
Hey!

I figured it would be cool to have the "+" operator in _core_add automatically do string conversions if one of the parameters is a string, so it could handle this: `"abc" + 3` like `"abc" + STR(3)` automatically. 

I copied some code out of _std_str into _core_add and tried to hack it together and had a little bit of success, but I suppose my way is not the best, so if you have a spare hour, I'm sure you'd do it much better than my hack :)

Cheers!

**Comment by paladin-t** [comment]
I suggest not to add this. Implicit conversion between string and number is considered harmful, it brings more troubles than benefits.

**Comment by iUltimateLP** [comment]
Thanks, could you elaborate why it exactly is considered harmful?

**Comment by paladin-t** [comment]
When a programmer see an expression, it's better to make it easy to tell what it does. The problem is that it becomes confusing if "42" can be implicitly calculated as `42` or vice versa. Eg. in `456 + "123"` does it results in "456123" or 579? And how about the following:

* `"123" + 456`
* `"123" - 456`
* `456 - "123"`
* `"123" <> 123`
* `123 <> "123"`

In JavaScript, there are similar [mistakes](https://www.w3schools.com/js/js_mistakes.asp) and more [gotcha moments](https://github.com/denysdovhan/wtfjs#funny-math), which are considered [design mistakes](https://www.programmersought.com/article/15191473314/), and should be avoided.

**Comment by iUltimateLP** [comment]
Ah I see, I guess once one of the operands is a string, one could assume that it should be a string append operation, but I see where you're coming from, and it probably makes more sense like that!
