### ISSUE TITLE
Different syntax

### ISSUE THREAD

**Issue by boogie** [paladin-t/my_basic#52]
I love this project. I would like to use it, but have a more C / JavaScript like syntax. Is there anyone interested in working on it with me?

**Comment by iUltimateLP** [comment]
Hey, I don't think it'll be that easy to implement a different syntax into my_basic as it'd require a whole different AST parsing. I'd recommend you to look at different libraries made for the syntax you're looking for, such as Lua, which is equally easy to integrate.

**Comment by boogie** [comment]
Thanks for your response. I don't want to offer Lua to my customers, I think it's hard to understand its tables and why indexing starts are 1. :) I have tried several other options, and available memory and flash storage is quite limited on my device, the best seems to be mybasic for me.

I will try to understand how parsing works, I like these challanges. Feel free to close this request.

**Comment by iUltimateLP** [comment]
Cool, I'm not in charge here but I'd keep it open for the matter as I'd love to see your process, and maybe @paladin-t can step in on questions?

**Comment by paladin-t** [comment]
The parser was not designed to support deep customization, dedicated tokens are used for different structures, i.e. `for ... next`, `while ... wend`, etc. It is not that simple to replace both `next` and `wend` to `}` instead.

However, I think it is possible to remould the parser to a C/JS like syntax by modifying `_parse_char`, `_create_symbol`, and maybe a few other functions, since the processing of the parsing pass is just a state machine.

**Comment by boogie** [comment]
Thanks Tony, I'll take a look.

**Comment by paladin-t** [comment]
Closing this. Feel free to issue other questions.
