### ISSUE TITLE
Custom function

### ISSUE THREAD

**Issue by julienkrief** [paladin-t/my_basic#6]
Hello,

I am at a loss to understand how i can define a custom NON-STATIC function in my cpp code.

exemple : 
int _customFunc(struct mb_interpreter_t* s, void** l) { ... }

register:
mb_register_func(bas, "customfunction", _customFunc);
==> this call cannot work without the "Static" prefix before "_customFunc"

Can you help me on this please?

Thanks :)

Julien

**Comment by paladin-t** [comment]
Hi,

It's not able to call a non-static method without an instance in C++, I mean you can't simply do that. But we are still able to do it with some tricks. The problem is C++ needs to know which instance a method will execute with, so we can store an instance and tell C++.

With MY-BASIC, for example, assume we got a C++ class:

	class AClass {

	public:
		void foo(void) const;

	};

Now I'd define some bridge function:

	int _a_new_instance(mb_interpreter_t* s, void** l) {
		// Creates an instance of AClass.

		mb_value_t ret;

		...

		mb_check(mb_attempt_open_bracket(s, l));

		mb_check(mb_attempt_close_bracket(s, l));

		ret.type = MB_DT_USERTYPE;
		ret.value.usertype = (void*)(new AClass);

		...
	}

	int _a_foo_bridge(mb_interpreter_t* s, void** l) {
		// Calls the foo method of an AClass instance.

		mb_value_t ret;
		AClass* inst = NULL;

		...

		mb_check(mb_attempt_open_bracket(s, l));

		mb_check(mb_pop_value(s, l, &a));

		mb_check(mb_attempt_close_bracket(s, l));

		inst = (AClass*)a.value.usertype;
		inst->foo();

		...
	}

Then in MY-BASIC code:

	a = a_new_instance()
	a_foo_bridge(a) ' Calls the foo method.

This is not the only way to call a non-static C++ method with C, it's just a simple practice. You could find a proper way by searching something like "call c++ method from c". There are also many ways to store a non-static method and its corresponding instance in a variable, you may would like to take a look at "function bind" if you were using C++11, or use the famous very lightweight [Fastdelegate](http://www.codeproject.com/Articles/7150/Member-Function-Pointers-and-the-Fastest-Possible) lib for C++.

BTW. MB_DT_USERTYPE_REF is more intelligent than MB_DT_USERTYPE, because MY-BASIC can manage the deallocation of a referenced object with Reference Counting and GC.

Best
WRX
