### ISSUE TITLE
Error and exception handling

### ISSUE THREAD

**Issue by niucool** [paladin-t/my_basic#7]
Great job, Renxin. Very neat and lightweight Basic interpreter. 
I wonder if it is possible to support VB syntax like On Error Statement and other keywords etc. ?

Thanks,
niucool

**Comment by paladin-t** [comment]
Hi niucool,

Good question. I've thought of 3 different ways, when I was considered supporting error handling.

1. VB style. On Error Goto/Resume;
	It's the most retro VB style. But I don't think it's the best error handling paradigm for modern programming.

2. Structured Exception Handling. Try-Catch-Finally, Throw;
	The common modern way.

3. Coroutine Based;
	Well, Coroutine would be much more than an error handling facility only, it organizes a chunk of runnable code as a whole, and could run concurrently.

It's not difficult to simply support On Error statement, but the most important thing when introducing a new feature is that keep the consistency with not only exist features, but also future ones. So I might introduce concurrent facility before advanced error handling.

Regards
WRX.

**Comment by niucool** [comment]
Thank you for your reply. 

What I'm thinking is a little bit different from yours. Basic is Basic, it should be easy to use and easy to port, I'd like my original basic code run properly with the help of my-basic without change or only minor changes. If my-basic introduces exclusive features or syntax, I have to learn,and these code are hard to port to other interpreters.
As VB is the most popular basic solution now, it will be great if my-basic could be compatible with it. 

Thanks,
niucool

**Comment by paladin-t** [comment]
That's considerable, niucool. But I doubt how many VB users have a purpose porting VB code with "On Error ..." handling code to MY-BASIC code, since Microsoft only reserved the On Error statements for compatibility from VB6 to VB.NET, and it's recommended to use [structured exception](https://msdn.microsoft.com/en-us/library/ms973849.aspx) by MS as well. I'd prefer to abandon that feature because of MB is not derived from VB directly. So at least it's not going to be implemented recently. Whatever, I'll keep it on my TODO note for a consideration.

Best
WRX.

**Comment by paladin-t** [comment]
Now it's possible to use [Structured exception handling](https://github.com/paladin-t/my_basic/wiki/Structured-exception-handling) with MY-BASIC.

**Comment by paladin-t** [comment]
SEH should be enough for most error handling cases. There won't be any more new features for v1.x. And it's still not sure whether the non-structured way will be introduced in the future.
